---
 
- hosts: webserver
  become: true
  tasks:
   - name: install apache
     apt: name=apache2 state=present

   - name: runservice
     service: name=apache2 state=started enabled=yes

   - name: display
     shell: echo myname > /var/www/html/index.html 

